---
- name: Update Linux Servers (Ubuntu/Debian)
  hosts: 10.11.2.44
  become: true
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
